// <auto-generated />
using System;
using Infraestrutura.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260130132408_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domínio.Model.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdUnidadeMedida")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUnidadeMedida");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Domínio.Model.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdReceitaPai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUnidadeMedida")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdReceitaPai");

                    b.HasIndex("IdUnidadeMedida");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("Domínio.Model.UnidadeDeMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadeDeMedida");
                });

            modelBuilder.Entity("Domínio.Model.VinculoReceitaMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMaterial")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdReceita")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("QuantidadeMaterial")
                        .HasColumnType("float");

                    b.Property<Guid>("materialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("receitaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("materialId");

                    b.HasIndex("receitaId");

                    b.ToTable("VinculoReceitaMaterial");
                });

            modelBuilder.Entity("Domínio.Model.Material", b =>
                {
                    b.HasOne("Domínio.Model.UnidadeDeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidadeMedida");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("Domínio.Model.Receita", b =>
                {
                    b.HasOne("Domínio.Model.Receita", "ReceitaPai")
                        .WithMany("SubReceitas")
                        .HasForeignKey("IdReceitaPai");

                    b.HasOne("Domínio.Model.UnidadeDeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidadeMedida");

                    b.Navigation("ReceitaPai");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("Domínio.Model.VinculoReceitaMaterial", b =>
                {
                    b.HasOne("Domínio.Model.Material", "material")
                        .WithMany("Vinculos")
                        .HasForeignKey("materialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domínio.Model.Receita", "receita")
                        .WithMany("Vinculos")
                        .HasForeignKey("receitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("material");

                    b.Navigation("receita");
                });

            modelBuilder.Entity("Domínio.Model.Material", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("Domínio.Model.Receita", b =>
                {
                    b.Navigation("SubReceitas");

                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
